"""add_soft_delete

Revision ID: 1571c7d748ce
Revises: 55cad1629895
Create Date: 2026-03-31 21:19:40.284824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1571c7d748ce'
down_revision: Union[str, Sequence[str], None] = '55cad1629895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('habits', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'deleted_at')
    op.drop_column('goals', 'deleted_at')
    # ### end Alembic commands ###
