"""add_pending_schedule

Revision ID: 544a0d1f56c2
Revises: 1571c7d748ce
Create Date: 2026-04-02 02:32:05.423007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544a0d1f56c2'
down_revision: Union[str, Sequence[str], None] = '1571c7d748ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('pending_schedule', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'pending_schedule')
    # ### end Alembic commands ###
