"""add context_id to habit_logs

Revision ID: 8e602c165269
Revises: 2667896058b1
Create Date: 2026-04-07 11:51:31.308334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e602c165269'
down_revision: Union[str, Sequence[str], None] = '2667896058b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_logs', sa.Column('context_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'habit_logs', 'context', ['context_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit_logs', type_='foreignkey')
    op.drop_column('habit_logs', 'context_id')
    # ### end Alembic commands ###
