"""add notification_sent to events

Revision ID: edf39a04b7d9
Revises: e2836d7fdc3b
Create Date: 2026-04-07 20:06:56.052126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf39a04b7d9'
down_revision: Union[str, Sequence[str], None] = 'e2836d7fdc3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_timestamp'), table_name='context')
    op.drop_index(op.f('ix_context_user_id'), table_name='context')
    op.add_column('events', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_habit_logs_completed_at'), table_name='habit_logs')
    op.drop_index(op.f('ix_habit_logs_context_id'), table_name='habit_logs')
    op.drop_index(op.f('ix_habit_logs_habit_id'), table_name='habit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_habit_logs_habit_id'), 'habit_logs', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_logs_context_id'), 'habit_logs', ['context_id'], unique=False)
    op.create_index(op.f('ix_habit_logs_completed_at'), 'habit_logs', ['completed_at'], unique=False)
    op.drop_column('events', 'notification_sent')
    op.create_index(op.f('ix_context_user_id'), 'context', ['user_id'], unique=False)
    op.create_index(op.f('ix_context_timestamp'), 'context', ['timestamp'], unique=False)
    # ### end Alembic commands ###
